name: Zephyr CI
on:
  push:
  pull_request:

env:
  ZEPHYR_VERSION: v4.2.0
  ZSDK_VER: 0.16.8

jobs:
  build-test-and-coverage:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: qemu_x86
            toolchain: zephyr
            do_coverage: false
          - board: native_sim
            toolchain: host
            do_coverage: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install base deps (apt)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            git cmake ninja-build ccache gperf dfu-util device-tree-compiler \
            wget python3-pip python3-setuptools python3-wheel xz-utils file make \
            gcc g++ libsdl2-dev lcov gcc-multilib g++-multilib

      - name: Install west
        run: |
          python3 -m pip install --upgrade pip
          pip3 install west

      - name: Initialize Zephyr workspace
        working-directory: ${{ github.workspace }}
        run: |
          mkdir -p zephyrproject
          west init -m https://github.com/zephyrproject-rtos/zephyr --mr "$ZEPHYR_VERSION" zephyrproject

      - name: Update Zephyr modules
        working-directory: ${{ github.workspace }}/zephyrproject
        run: |
          west update
          west zephyr-export
          pip3 install -r zephyr/scripts/requirements.txt

      # Remove "dubious ownership" / exit code 128 warnings from git in nested repos
      - name: Mark Zephyr repos as safe for git
        working-directory: ${{ github.workspace }}/zephyrproject
        run: |
          for d in $(git rev-parse --show-toplevel 2>/dev/null || true) \
                   $(find "$GITHUB_WORKSPACE/zephyrproject" -name .git -type d -prune -print | sed 's|/.git$||'); do
            git config --global --add safe.directory "$d" || true
          done

      # Toolchain selection per matrix
      - name: Use Zephyr SDK toolchain
        if: matrix.toolchain == 'zephyr'
        run: |
          cd "$HOME"
          wget -q https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v${ZSDK_VER}/zephyr-sdk-${ZSDK_VER}_linux-x86_64.tar.xz
          tar -xJf zephyr-sdk-${ZSDK_VER}_linux-x86_64.tar.xz
          "${HOME}/zephyr-sdk-${ZSDK_VER}/setup.sh" -t all -h -c
          echo "ZEPHYR_TOOLCHAIN_VARIANT=zephyr" >> "$GITHUB_ENV"
          echo "ZEPHYR_SDK_INSTALL_DIR=${HOME}/zephyr-sdk-${ZSDK_VER}" >> "$GITHUB_ENV"

      - name: Use host toolchain (for native_sim)
        if: matrix.toolchain == 'host'
        run: echo "ZEPHYR_TOOLCHAIN_VARIANT=host" >> "$GITHUB_ENV"

      - name: Sanity check west workspace
        working-directory: ${{ github.workspace }}/zephyrproject
        run: |
          west topdir
          west --version

      - name: Build app
        working-directory: ${{ github.workspace }}/zephyrproject
        run: |
          west build -b "${{ matrix.board }}" \
            -s "$GITHUB_WORKSPACE/apps/secure_counter" \
            -d "$GITHUB_WORKSPACE/build/${{ matrix.board }}"

      - name: Smoke run (short)
        working-directory: ${{ github.workspace }}/zephyrproject
        run: |
          timeout 8s ninja -C "$GITHUB_WORKSPACE/build/${{ matrix.board }}" run || true

      - name: Run Twister (qemu_x86 only)
        if: matrix.board == 'qemu_x86'
        working-directory: ${{ github.workspace }}/zephyrproject/zephyr
        run: |
          ./scripts/twister -T "$GITHUB_WORKSPACE/apps/secure_counter/tests" \
            -p qemu_x86 --jobs 2 -v

      - name: Coverage (native_sim only)
        if: matrix.do_coverage == 'true'
        working-directory: ${{ github.workspace }}/zephyrproject
        run: |
          # Build with coverage overlay
          west build -b native_sim \
            -s "$GITHUB_WORKSPACE/apps/secure_counter" \
            -d "$GITHUB_WORKSPACE/build/secure_counter_cov" \
            -- -DOVERLAY_CONFIG="$GITHUB_WORKSPACE/apps/secure_counter/overlay-coverage.conf"

          # Run briefly to produce .gcda files
          timeout 8s ninja -C "$GITHUB_WORKSPACE/build/secure_counter_cov" run || true

          # Capture coverage (raw)
          lcov --capture \
            --directory "$GITHUB_WORKSPACE/build/secure_counter_cov/zephyr" \
            --output-file "$GITHUB_WORKSPACE/coverage.full.info"

          # Try absolute path extraction first
          lcov --extract "$GITHUB_WORKSPACE/coverage.full.info" \
            "$GITHUB_WORKSPACE/apps/secure_counter/*" \
            -o "$GITHUB_WORKSPACE/coverage.app.info" || true

          # Fallback: rewrite CMAKE_SOURCE_DIR paths, then extract
          if ! grep -q '^SF:' "$GITHUB_WORKSPACE/coverage.app.info"; then
            sed "s#CMAKE_SOURCE_DIR#${GITHUB_WORKSPACE}/apps/secure_counter#g" \
              "$GITHUB_WORKSPACE/coverage.full.info" > "$GITHUB_WORKSPACE/coverage.rewritten.info"
            lcov --extract "$GITHUB_WORKSPACE/coverage.rewritten.info" \
              "$GITHUB_WORKSPACE/apps/secure_counter/*" \
              -o "$GITHUB_WORKSPACE/coverage.app.info"
          fi

          # Generate HTML
          genhtml "$GITHUB_WORKSPACE/coverage.app.info" \
            --output-directory "$GITHUB_WORKSPACE/coverage-report" \
            --title "Secure Counter coverage"

      - name: Upload coverage HTML
        if: matrix.do_coverage == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coverage-report
          if-no-files-found: warn

      - name: Upload lcov files
        if: matrix.do_coverage == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: lcov-files
          path: |
            coverage.full.info
            coverage.app.info
            coverage.rewritten.info
          if-no-files-found: warn

      - name: Upload Twister report
        if: matrix.board == 'qemu_x86'
        uses: actions/upload-artifact@v4
        with:
          name: twister-out
          path: zephyrproject/zephyr/twister-out
          if-no-files-found: warn
